#!/bin/bash

file="$1"

if [ ! ${file: -6} == ".ipynb" ] ; then
    exit 0
fi

if [[ $file =~ "nbsearch-tmp" ]] ; then
    exit 0
fi

jupyter nbsearch update-index --debug $CONDA_DIR/etc/jupyter/jupyter_notebook_config.py local $file
exit 0